var generalKey=0;
var chordsPlayed=[];
var chordDistances=[];
var listnotes=[];
var circleOfFifthForMode=[1,5,2,6,3,7,4];
var circleOfFifthForKey=[0,7,2,9,4,11,6,1,8,3,10,5];
var keysshown=false;
var maxtonal=0;
var maxmode=[0,0,0,0,0,0,0,0,0,0,0,0];
var game_state = 0;
var heightsForLeaves=[];
var widthsForLeaves=[];
var widthsForLeavesMirrored=[];
var chordsPlayedNoDup=[];
const keys = "q2we4r5ty7u8i9opazsxcfvgbhnmk";
var notes=[];
var duration=4;
var selectedPreset=_tone_0000_Aspirin_sf2_file;
var AudioContextFunc = window.AudioContext || window.webkitAudioContext;
var audioContext = new AudioContextFunc();
var player=new WebAudioFontPlayer();

let angle=0;
let scale=1;
let truckLength=1;
let truckScale=0.3;
let truckSuperposition=(920-196)*truckScale;
let scalePlantTrunk=1;
let truckPlantSuperposition=1;
let colorBranch;
let branchY=[];
let branchX=[];
let angles=[50,140,50,140,50,140,50];
let anglesMirrored=[310,220,310,220,310,220,310];
let anglesForLeaves=[];
let anglesForLeavesMirrored=[];
let onOff=0;
let l3;

let position_x;
let position_y;
let pos_angle ;
let a=0;